# version: '3.8'

# services:
#   web-app:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./envirotrack:/envirotrack
#     environment:
#       - DB_ENGINE=django.db.backends.postgresql
#       - DB_NAME=dbname
#       - DB_USER=dbuser
#       - DB_PASS=pass
#       - DB_HOST=database
#       - DB_PORT=5432
#     depends_on:
#       - database
#     command: sh -c "python manage.py migrate && python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', '', 'pass')\" && gunicorn envirotrack.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level debug"
#     networks:
#       - envirotrack-network

#   database:
#     image: postgres:latest
#     environment:
#       - POSTGRES_DB=dbname
#       - POSTGRES_USER=dbuser
#       - POSTGRES_PASSWORD=pass
#     ports:
#       - "5432:5432"
#     networks:
#       - envirotrack-network

#   web-app-frontend:
#     build: 
#       context: ./envirotrack/frontend  
#       dockerfile: Dockerfile.frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#     depends_on:
#       - web-app
#     networks:
#       - envirotrack-network

#   redis:
#     image: redis:7.0.5-alpine
#     hostname: redis

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ./envirotrack/frontend/build:/app/frontend/build
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - web-app
#     networks:
#       - envirotrack-network

# networks:
#   envirotrack-network:
#     driver: bridge


version: '3.8'

services:
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./envirotrack:/envirotrack
      - ./backups:/backups  # Монтируем директорию для бэкапов
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
      - DB_HOST=database
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - database
      - redis
    command: sh -c "python manage.py migrate && python manage.py shell -c \"from django.contrib.auth.models import User; User.objects.filter(username='admin').exists() or User.objects.create_superuser('admin', '', 'pass')\" && gunicorn envirotrack.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level debug"
    networks:
      - envirotrack-network

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    networks:
      - envirotrack-network

  web-app-frontend:
    build: 
      context: ./envirotrack/frontend  
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - web-app
    networks:
      - envirotrack-network

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    networks:
      - envirotrack-network

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A envirotrack worker --loglevel=info
    volumes:
      - ./envirotrack:/envirotrack
      - ./backups:/backups  # Монтируем директорию для бэкапов
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
      - DB_HOST=database
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - web-app
      - redis
    networks:
      - envirotrack-network

  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: celery -A envirotrack beat --loglevel=info
    volumes:
      - ./envirotrack:/envirotrack
      - ./backups:/backups  # Монтируем директорию для бэкапов
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
      - DB_HOST=database
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - web-app
      - redis
    networks:
      - envirotrack-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./envirotrack/frontend/build:/app/frontend/build
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-app
    networks:
      - envirotrack-network

networks:
  envirotrack-network:
    driver: bridge