# Generated by Django 4.1.7 on 2023-10-22 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_parameterset_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 10, 22, 18, 12, 11, 372051, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
