# Generated by Django 4.1.7 on 2023-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_parameterset_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
