# Generated by Django 4.2.7 on 2024-03-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_enviromentalparameters_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurementinstrument',
            options={'verbose_name': 'Средство измерений', 'verbose_name_plural': 'Средства измерений'},
        ),
    ]
