# Generated by Django 4.2.7 on 2024-03-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_measurementinstrument_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='humidity_max',
            field=models.FloatField(default=100, verbose_name='Максимальная влажность'),
        ),
        migrations.AddField(
            model_name='room',
            name='humidity_min',
            field=models.FloatField(default=0, verbose_name='Минимальная влажность'),
        ),
        migrations.AddField(
            model_name='room',
            name='pressure_max_kpa',
            field=models.FloatField(default=100, verbose_name='Максимальное давление (кПа)'),
        ),
        migrations.AddField(
            model_name='room',
            name='pressure_max_mmhg',
            field=models.FloatField(default=760, verbose_name='Максимальное давление (мм рт. ст.)'),
        ),
        migrations.AddField(
            model_name='room',
            name='pressure_min_kpa',
            field=models.FloatField(default=0, verbose_name='Минимальное давление (кПа)'),
        ),
        migrations.AddField(
            model_name='room',
            name='pressure_min_mmhg',
            field=models.FloatField(default=0, verbose_name='Минимальное давление (мм рт. ст.)'),
        ),
        migrations.AddField(
            model_name='room',
            name='temperature_max',
            field=models.FloatField(default=100, verbose_name='Максимальная температура'),
        ),
        migrations.AddField(
            model_name='room',
            name='temperature_min',
            field=models.FloatField(default=0, verbose_name='Минимальная температура'),
        ),
    ]
