# Generated by Django 5.0.3 on 2024-03-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_room_humidity_max_room_humidity_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementinstrument',
            name='metrological_characteristics',
            field=models.CharField(default='', max_length=255, verbose_name='Метрологические характеристики СИ'),
        ),
        migrations.AddField(
            model_name='measurementinstrument',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей поверки'),
        ),
        migrations.AddField(
            model_name='measurementinstrument',
            name='registration_number',
            field=models.CharField(default='', max_length=50, verbose_name='Регистрационный номер СИ'),
        ),
        migrations.AddField(
            model_name='measurementinstrument',
            name='suitability',
            field=models.BooleanField(default=True, verbose_name='Пригодность СИ'),
        ),
        migrations.AddField(
            model_name='measurementinstrument',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(default=2000, verbose_name='Год выпуска СИ'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_number', models.CharField(max_length=10, verbose_name='Номер здания')),
                ('voltage_min', models.FloatField(default=0, verbose_name='Минимальное напряжение питающей сети (В)')),
                ('voltage_max', models.FloatField(default=1000, verbose_name='Максимальное напряжение питающей сети (В)')),
                ('frequency_min', models.FloatField(default=0, verbose_name='Минимальная частота переменного тока (Гц)')),
                ('frequency_max', models.FloatField(default=60, verbose_name='Максимальная частота переменного тока (Гц)')),
                ('responsible_persons', models.ManyToManyField(related_name='buildings', to='backend.responsible', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='building',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='backend.building', verbose_name='Здание'),
            preserve_default=False,
        ),
    ]
