# Generated by Django 5.0.3 on 2024-03-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_measurementinstrument_metrological_characteristics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementinstrument',
            name='responsible_persons',
            field=models.ManyToManyField(related_name='measurement_instruments', to='backend.responsible', verbose_name='Ответственный'),
        ),
    ]
