# Generated by Django 5.0.3 on 2024-03-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_measurementinstrument_responsible_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementinstrument',
            name='responsible_persons',
            field=models.ManyToManyField(blank=True, related_name='measurement_instruments', to='backend.responsible', verbose_name='Ответственный'),
        ),
    ]
