# Generated by Django 5.0.3 on 2024-03-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_measurementinstrument_responsible_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementinstrument',
            name='responsible_persons',
        ),
    ]
