# Generated by Django 5.0.3 on 2024-04-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_measurementinstrument_responsible_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
