# Generated by Django 5.0.3 on 2024-04-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_enviromentalparameters_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingParameterSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField(verbose_name='Напряжение питающей сети (В)')),
                ('frequency', models.FloatField(verbose_name='Частота переменного тока (Гц)')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время записи')),
            ],
            options={
                'verbose_name': 'Набор параметров для здания',
                'verbose_name_plural': 'Наборы параметров для здания',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='has_additional_parameters',
            field=models.BooleanField(default=False, verbose_name='Использует дополнительные параметры'),
        ),
        migrations.CreateModel(
            name='AdditionalParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Минимальное напряжение (В)')),
                ('voltage_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Максимальное напряжение (В)')),
                ('frequency_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Минимальная частота (Гц)')),
                ('frequency_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Максимальная частота (Гц)')),
                ('radiation_min', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Минимальный радиационный фон')),
                ('radiation_max', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Максимальный радиационный фон')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_parameters', to='backend.room', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Дополнительные параметры',
                'verbose_name_plural': 'Дополнительные параметры',
            },
        ),
        migrations.CreateModel(
            name='BuildingEnviromentalParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_environmental_parameters', to='backend.building', verbose_name='Здание')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_building_parameters', to=settings.AUTH_USER_MODEL)),
                ('measurement_instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.measurementinstrument')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_building_parameters', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_environmental_parameters', to='backend.responsible')),
                ('parameter_sets', models.ManyToManyField(blank=True, related_name='building_environmental_parameters', to='backend.buildingparameterset')),
            ],
            options={
                'verbose_name': 'Параметры окружающей среды для здания',
                'verbose_name_plural': 'Параметры окружающей среды для зданий',
            },
        ),
    ]
