# Generated by Django 5.0.3 on 2024-04-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_buildingparameterset_room_has_additional_parameters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedParameterSet',
            fields=[
                ('parameterset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.parameterset')),
                ('voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('radiation', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Расширенный набор параметров',
                'verbose_name_plural': 'Расширенные наборы параметров',
            },
            bases=('backend.parameterset',),
        ),
    ]
