# Generated by Django 5.0.3 on 2024-04-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_buildingparameterset_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviromentalparameters',
            options={'verbose_name': 'Запись с параметрами окружающей среды', 'verbose_name_plural': 'Записи с параметрами окружающей среды'},
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='extended_parameter_sets',
            field=models.ManyToManyField(blank=True, related_name='extended_parameter_sets_related', to='backend.extendedparameterset'),
        ),
    ]
