# Generated by Django 5.0.3 on 2024-04-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_enviromentalparameters_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='extended_parameter_sets',
            field=models.ManyToManyField(blank=True, related_name='environmental_parameters_extended_parameter_sets', to='backend.extendedparameterset'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='parameter_sets',
            field=models.ManyToManyField(blank=True, related_name='environmental_parameters_parameter_sets', to='backend.parameterset'),
        ),
    ]
