# Generated by Django 5.0.3 on 2024-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_enviromentalparameters_extended_parameter_sets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingenviromentalparameters',
            name='measurement_instrument',
        ),
        migrations.RemoveField(
            model_name='enviromentalparameters',
            name='measurement_instrument',
        ),
        migrations.AddField(
            model_name='buildingenviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(null=True, to='backend.measurementinstrument'),
        ),
        migrations.AddField(
            model_name='enviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(null=True, to='backend.measurementinstrument'),
        ),
    ]
