# Generated by Django 5.0.3 on 2024-04-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_buildingenviromentalparameters_measurement_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalparameters',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_parameters', to='backend.room', verbose_name='Помещение'),
        ),
    ]
