# Generated by Django 5.0.3 on 2024-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_alter_additionalparameters_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalparameters',
            name='room',
        ),
        migrations.AddField(
            model_name='additionalparameters',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, related_name='additional_parameters', to='backend.room', verbose_name='Помещение'),
        ),
    ]
