# Generated by Django 5.0.3 on 2024-04-21 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_remove_additionalparameters_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalparameters',
            name='room',
        ),
        migrations.AddField(
            model_name='additionalparameters',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_parameters', to='backend.room', verbose_name='Помещение'),
        ),
    ]
