# Generated by Django 5.0.3 on 2024-04-21 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_additionalparameters_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalparameters',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='additional_parameters',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='backend.additionalparameters', verbose_name='Дополнительные параметры'),
        ),
    ]
