# Generated by Django 5.0.3 on 2024-04-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_remove_room_additional_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_storage',
            field=models.BooleanField(default=False, verbose_name='Кладовая временного хранения'),
        ),
    ]
