# Generated by Django 5.0.3 on 2024-04-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_room_is_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetForStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Набор параметров для КВХ',
                'verbose_name_plural': 'Наборы параметров КВХ',
            },
        ),
    ]
