# Generated by Django 5.0.3 on 2024-04-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_parametersetforstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='enviromentalparameters',
            name='parameter_sets_for_storage',
            field=models.ManyToManyField(blank=True, related_name='environmental_parameters_parameter_sets_for_storage', to='backend.parametersetforstorage'),
        ),
    ]
