# Generated by Django 5.0.3 on 2024-04-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_enviromentalparameters_parameter_sets_for_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='pressure_kpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='pressure_mmhg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
