# Generated by Django 4.2.13 on 2024-10-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_alter_parameterset_pressure_kpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingparameterset',
            name='harmonic_coefficient',
            field=models.FloatField(default=0, help_text='Введите значение в процентах. Например, 4.3 означает 4.3%', verbose_name='Коэффициент несинусоидальности кривой напряжения (коэффициент гармоник)'),
        ),
        migrations.AddField(
            model_name='buildingparameterset',
            name='waveform_shape',
            field=models.CharField(default='синусоидальная', max_length=100, verbose_name='Форма кривой переменного напряжения питающей сети'),
        ),
    ]
