# Generated by Django 4.2.13 on 2025-01-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='Responsible_list/', verbose_name='Список ответственных')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='userguide/', verbose_name='Руководство пользователя'),
        ),
    ]
