# Generated by Django 4.2.13 on 2025-01-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_responsiblelist_alter_document_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Руководство пользователя', 'verbose_name_plural': 'Руководства пользователя'},
        ),
        migrations.AlterModelOptions(
            name='responsiblelist',
            options={'verbose_name': 'Список ответственных', 'verbose_name_plural': 'Списки ответственных'},
        ),
    ]
