# Generated by Django 4.2.13 on 2025-12-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_document_options_alter_responsiblelist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviromentalparameters',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запись с параметрами окружающей среды', 'verbose_name_plural': 'Записи с параметрами окружающей среды'},
        ),
        migrations.AlterField(
            model_name='building',
            name='building_number',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Номер здания'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='created_at',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(blank=True, to='backend.measurementinstrument'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='buildingparameterset',
            name='frequency',
            field=models.FloatField(db_index=True, verbose_name='Частота переменного тока (Гц)'),
        ),
        migrations.AlterField(
            model_name='buildingparameterset',
            name='voltage',
            field=models.FloatField(db_index=True, verbose_name='Напряжение питающей сети (В)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='created_at',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(blank=True, to='backend.measurementinstrument'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='frequency',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='radiation',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='voltage',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='calibration_date',
            field=models.DateField(db_index=True, verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='next_calibration_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата следующей поверки'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='registration_number',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='Регистрационный номер СИ'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='suitability',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Пригодность СИ'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='type',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='humidity_percentage',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='temperature_celsius',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametersetforstorage',
            name='humidity_percentage',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametersetforstorage',
            name='temperature_celsius',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='responsiblelist',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='responsiblelist',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_additional_parameters',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Использует дополнительные параметры'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_storage',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Кладовая временного хранения'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Номер помещения'),
        ),
        migrations.AddIndex(
            model_name='buildingenviromentalparameters',
            index=models.Index(fields=['building', 'created_at'], name='backend_bui_buildin_ae85f6_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingenviromentalparameters',
            index=models.Index(fields=['responsible', 'created_at'], name='backend_bui_respons_1a3033_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingparameterset',
            index=models.Index(fields=['voltage'], name='backend_bui_voltage_bf9cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='buildingparameterset',
            index=models.Index(fields=['frequency'], name='backend_bui_frequen_820f0d_idx'),
        ),
        migrations.AddIndex(
            model_name='enviromentalparameters',
            index=models.Index(fields=['room', 'created_at'], name='backend_env_room_id_15087e_idx'),
        ),
        migrations.AddIndex(
            model_name='enviromentalparameters',
            index=models.Index(fields=['responsible', 'created_at'], name='backend_env_respons_c0effc_idx'),
        ),
        migrations.AddIndex(
            model_name='enviromentalparameters',
            index=models.Index(fields=['created_at'], name='backend_env_created_330906_idx'),
        ),
        migrations.AddIndex(
            model_name='enviromentalparameters',
            index=models.Index(fields=['created_by', 'created_at'], name='backend_env_created_141dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='enviromentalparameters',
            index=models.Index(fields=['room', 'responsible', 'created_at'], name='backend_env_room_id_f23dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='extendedparameterset',
            index=models.Index(fields=['voltage'], name='backend_ext_voltage_a63345_idx'),
        ),
        migrations.AddIndex(
            model_name='extendedparameterset',
            index=models.Index(fields=['frequency'], name='backend_ext_frequen_012839_idx'),
        ),
        migrations.AddIndex(
            model_name='extendedparameterset',
            index=models.Index(fields=['radiation'], name='backend_ext_radiati_70a733_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementinstrument',
            index=models.Index(fields=['suitability'], name='backend_mea_suitabi_88bc46_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementinstrument',
            index=models.Index(fields=['calibration_date'], name='backend_mea_calibra_956cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementinstrument',
            index=models.Index(fields=['next_calibration_date'], name='backend_mea_next_ca_876935_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementinstrument',
            index=models.Index(fields=['name', 'type'], name='backend_mea_name_367daf_idx'),
        ),
        migrations.AddIndex(
            model_name='parameterset',
            index=models.Index(fields=['temperature_celsius'], name='backend_par_tempera_0e43f7_idx'),
        ),
        migrations.AddIndex(
            model_name='parameterset',
            index=models.Index(fields=['humidity_percentage'], name='backend_par_humidit_a19f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='parametersetforstorage',
            index=models.Index(fields=['temperature_celsius'], name='backend_par_tempera_e743ea_idx'),
        ),
        migrations.AddIndex(
            model_name='parametersetforstorage',
            index=models.Index(fields=['humidity_percentage'], name='backend_par_humidit_b7b46f_idx'),
        ),
        migrations.AddIndex(
            model_name='responsible',
            index=models.Index(fields=['last_name', 'first_name'], name='backend_res_last_na_665183_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['building', 'room_number'], name='backend_roo_buildin_e42b10_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_storage', 'has_additional_parameters'], name='backend_roo_is_stor_c5cf2f_idx'),
        ),
    ]
