# Generated by Django 4.2.13 on 2025-12-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_enviromentalparameters_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enviromentalparameters',
            options={'verbose_name': 'Запись с параметрами окружающей среды', 'verbose_name_plural': 'Записи с параметрами окружающей среды'},
        ),
        migrations.RemoveIndex(
            model_name='buildingenviromentalparameters',
            name='backend_bui_buildin_ae85f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='buildingenviromentalparameters',
            name='backend_bui_respons_1a3033_idx',
        ),
        migrations.RemoveIndex(
            model_name='buildingparameterset',
            name='backend_bui_voltage_bf9cbc_idx',
        ),
        migrations.RemoveIndex(
            model_name='buildingparameterset',
            name='backend_bui_frequen_820f0d_idx',
        ),
        migrations.RemoveIndex(
            model_name='enviromentalparameters',
            name='backend_env_room_id_15087e_idx',
        ),
        migrations.RemoveIndex(
            model_name='enviromentalparameters',
            name='backend_env_respons_c0effc_idx',
        ),
        migrations.RemoveIndex(
            model_name='enviromentalparameters',
            name='backend_env_created_330906_idx',
        ),
        migrations.RemoveIndex(
            model_name='enviromentalparameters',
            name='backend_env_created_141dd7_idx',
        ),
        migrations.RemoveIndex(
            model_name='enviromentalparameters',
            name='backend_env_room_id_f23dfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='extendedparameterset',
            name='backend_ext_voltage_a63345_idx',
        ),
        migrations.RemoveIndex(
            model_name='extendedparameterset',
            name='backend_ext_frequen_012839_idx',
        ),
        migrations.RemoveIndex(
            model_name='extendedparameterset',
            name='backend_ext_radiati_70a733_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurementinstrument',
            name='backend_mea_suitabi_88bc46_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurementinstrument',
            name='backend_mea_calibra_956cc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurementinstrument',
            name='backend_mea_next_ca_876935_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurementinstrument',
            name='backend_mea_name_367daf_idx',
        ),
        migrations.RemoveIndex(
            model_name='parameterset',
            name='backend_par_tempera_0e43f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='parameterset',
            name='backend_par_humidit_a19f8c_idx',
        ),
        migrations.RemoveIndex(
            model_name='parametersetforstorage',
            name='backend_par_tempera_e743ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='parametersetforstorage',
            name='backend_par_humidit_b7b46f_idx',
        ),
        migrations.RemoveIndex(
            model_name='responsible',
            name='backend_res_last_na_665183_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='backend_roo_buildin_e42b10_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='backend_roo_is_stor_c5cf2f_idx',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_number',
            field=models.CharField(max_length=10, verbose_name='Номер здания'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(null=True, to='backend.measurementinstrument'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buildingparameterset',
            name='frequency',
            field=models.FloatField(verbose_name='Частота переменного тока (Гц)'),
        ),
        migrations.AlterField(
            model_name='buildingparameterset',
            name='voltage',
            field=models.FloatField(verbose_name='Напряжение питающей сети (В)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(null=True, to='backend.measurementinstrument'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='frequency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='radiation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='calibration_date',
            field=models.DateField(verbose_name='Дата поверки'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='next_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей поверки'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='registration_number',
            field=models.CharField(default='', max_length=50, verbose_name='Регистрационный номер СИ'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='serial_number',
            field=models.CharField(max_length=50, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='suitability',
            field=models.BooleanField(default=True, verbose_name='Пригодность СИ'),
        ),
        migrations.AlterField(
            model_name='measurementinstrument',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='humidity_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='temperature_celsius',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametersetforstorage',
            name='humidity_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametersetforstorage',
            name='temperature_celsius',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='profession',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='responsiblelist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='responsiblelist',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_additional_parameters',
            field=models.BooleanField(default=False, verbose_name='Использует дополнительные параметры'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_storage',
            field=models.BooleanField(default=False, verbose_name='Кладовая временного хранения'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='Номер помещения'),
        ),
    ]
