# Generated by Django 4.2.13 on 2026-10-04 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0034_humidity_one_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_building_parameters', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(to='backend.measurementinstrument', verbose_name='Средства измерений'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_building_parameters', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='parameter_sets',
            field=models.ManyToManyField(blank=True, related_name='building_environmental_parameters', to='backend.buildingparameterset', verbose_name='Наборы параметров'),
        ),
        migrations.AlterField(
            model_name='buildingenviromentalparameters',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_environmental_parameters', to='backend.responsible', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='buildingparameterset',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='created_at',
            field=models.DateField(null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_parameters', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='extended_parameter_sets',
            field=models.ManyToManyField(blank=True, related_name='environmental_parameters_extended_parameter_sets', to='backend.extendedparameterset', verbose_name='Расширенные наборы параметров'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='measurement_instruments',
            field=models.ManyToManyField(to='backend.measurementinstrument', verbose_name='Средства измерений'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_parameters', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='parameter_sets',
            field=models.ManyToManyField(blank=True, related_name='environmental_parameters_parameter_sets', to='backend.parameterset', verbose_name='Наборы параметров'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='parameter_sets_for_storage',
            field=models.ManyToManyField(blank=True, related_name='environmental_parameters_parameter_sets_for_storage', to='backend.parametersetforstorage', verbose_name='Наборы параметров КВХ'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_parameters', to='backend.responsible', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='enviromentalparameters',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.room', verbose_name='Помещение'),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='frequency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Частота (Гц)'),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='radiation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Радиационный фон'),
        ),
        migrations.AlterField(
            model_name='extendedparameterset',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Напряжение (В)'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='humidity_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Влажность (%)'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='pressure_kpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Давление (кПа)'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='pressure_mmhg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Давление (мм рт. ст.)'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='temperature_celsius',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура (°C)'),
        ),
        migrations.AlterField(
            model_name='parameterset',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='parametersetforstorage',
            name='humidity_percentage',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Влажность (%)'),
        ),
        migrations.AlterField(
            model_name='parametersetforstorage',
            name='temperature_celsius',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Температура (°C)'),
        ),
        migrations.AlterField(
            model_name='parametersetforstorage',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.CreateModel(
            name='UserFilterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('rooms', 'Записи по помещениям'), ('buildings', 'Записи по зданиям')], max_length=20, verbose_name='Раздел')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Фильтры')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сохранённый фильтр',
                'verbose_name_plural': 'Сохранённые фильтры',
            },
        ),
        migrations.AddConstraint(
            model_name='userfilterpreference',
            constraint=models.UniqueConstraint(fields=('user', 'scope'), name='unique_filter_preference_per_scope'),
        ),
    ]
